version: "3.7"

### Securing ports withing docker: https://dev.to/kovah/be-careful-with-docker-ports-3pih

services:
 
  # dstrategy instance
  dstrategy1:
    image: dwxalphateam/mendelframework:dstrategy1
    container_name: dstrategy1
    hostname: dstrategy1
    networks:
      - darwinex_network
    logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
    # Create volume: host:docker > The files will be in the root directory.
    volumes:
      - /root/mendel-framework/D-Strategy1/APICredentials.json:/APICredentials.json
    restart: "no"

networks:
  darwinex_network:
    name: darwinex_network